CREATE TABLE IF NOT EXISTS
workManager.items(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    type_id BIGINT UNSIGNED NOT NULL COMMENT "type id",
    name VARCHAR(255) NOT NULL,
    amount INT NOT NULL DEFAULT 0 COMMENT "amount of item",
    contain INT NOT NULL DEFAULT 0 COMMENT "contains by amount",
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    FOREIGN KEY (type_id)
      REFERENCES types(id)
      ON DELETE CASCADE,
    PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;
