CREATE TABLE IF NOT EXISTS
workManager.logs(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  item_id BIGINT UNSIGNED NOT NULL COMMENT "item id",
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL,
  FOREIGN KEY (item_id)
    REFERENCES items(id)
    ON DELETE CASCADE,
  PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4
