CREATE TABLE IF NOT EXISTS
workManager.users(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL COMMENT "User Name",
  email VARCHAR(35) NOT NULL COMMENT "User Email",
  password VARCHAR(40) NOT NULL COMMENT "User Password",
  bio VARCHAR(255) COMMENT "User Profile",
  website VARCHAR(255) COMMENT "User Website",
  image VARCHAR(255) COMMENT "User Profile Image",
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL,
  PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;