CREATE TABLE IF NOT EXISTS
workManager.posts(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL COMMENT "投稿したユーザーID",
  content VARCHAR(999) COMMENT "投稿内容",
  PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;