CREATE TABLE IF NOT EXISTS
workManager.likes(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  post_id BIGINT UNSIGNED NOT NULL,
  type BIT NOT NULL COMMENT "いいね 悪いね",
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id)
    REFERENCES users(id),
  FOREIGN KEY (post_id)
    REFERENCES posts(id),
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4